# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def reactive_swift
  pod 'ReactiveSwift', '~> 6.1'
end

def reactive_cocoa
  pod 'ReactiveCocoa', '~> 10.1'
end

def reactive_dependencies
  reactive_swift
  reactive_cocoa
end

target 'ReactiveSwiftTests' do
  use_frameworks!
  reactive_dependencies
end

target 'ReactiveSwiftTestsCore' do
  use_frameworks!
  reactive_dependencies
end

target 'ReactiveSwiftTestsCoreiOS' do
  use_frameworks!
  reactive_dependencies
end


post_install do |pi|
    pi.pods_project.targets.each do |t|
        t.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
        end
    end
end
